#!/bin/bash

set -euo pipefail

# exit early if not in github actions CI
if [[ "${GITHUB_ACTIONS:-}" == "" ]]; then
    echo "-r testpypi"
    exit 0
fi

if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
  branch="${GITHUB_REF##*/}"
  if [[ "${branch}" != "main" && "${branch}" != "master" ]]; then
      echo "-r testpypi"
  else
      # post-PR merge, publish to official
      exit 0
  fi
elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
  echo "-r testpypi"
else
  echo "Invalid branch"
  exit 1
fi

exit 0
